/**
 * Emits the cross-language contract artifacts that the Python service checks
 * itself against.
 *
 *   pnpm --filter @workspace/contracts run export-wire
 *
 * Output (git-committed, never hand-edited):
 *   dist-wire/wire.json    — Temporal task queue / workflow / signal / query / activity names
 *   dist-wire/schema.json  — JSON Schema for every schema crossing the language boundary
 *
 * TypeScript is the source of truth because the UI and Mastra consume these
 * types directly and would notice a break at compile time. Python asserts
 * agreement at test time. Neither side can silently drift.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod/v4";

import { WIRE_MANIFEST } from "../src/wire";
import { CatalogComponent } from "../src/catalog";
import { CommerceQuote } from "../src/commerce";
import { EngineeringAssessment } from "../src/engineering";
import { AssistantProposal } from "../src/proposal";
import { ResolvedConfiguration, UIManifest } from "../src/manifest";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "..", "dist-wire");

/** Every schema that travels between TypeScript and Python. */
const CROSS_LANGUAGE_SCHEMAS = {
  CatalogComponent,
  EngineeringAssessment,
  CommerceQuote,
  ResolvedConfiguration,
  AssistantProposal,
  UIManifest,
} as const;

const schemas: Record<string, unknown> = {};
for (const [name, schema] of Object.entries(CROSS_LANGUAGE_SCHEMAS)) {
  // `io: "input"` so defaults appear as optional — matches how Python will
  // construct these objects, rather than how TypeScript reads them back.
  schemas[name] = z.toJSONSchema(schema as z.ZodType, {
    io: "input",
    unrepresentable: "any",
  });
}

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, "wire.json"), JSON.stringify(WIRE_MANIFEST, null, 2) + "\n");
writeFileSync(
  resolve(outDir, "schema.json"),
  JSON.stringify({ $comment: "GENERATED by export-wire.ts — do not edit", schemas }, null, 2) + "\n",
);

console.log(`wrote ${Object.keys(schemas).length} schemas + wire manifest to ${outDir}`);
